# Generated by Django 3.1.1 on 2020-09-02 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('custom_name', models.CharField(max_length=50, null=True)),
                ('number', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=3)),
                ('cashtag', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name', 'card_number')},
            },
        ),
    ]
