# Generated by Django 3.1.1 on 2020-09-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('description', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=50, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference', models.CharField(max_length=50, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('transaction_currency', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=50)),
                ('custom_category', models.CharField(max_length=50, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'unique_together': {('account', 'transaction_id')},
            },
        ),
    ]
